export const projectSpectraChapters = [
  {
    id: "intro",
    title: "Project Spectra: Introduction",
    video: "/videos/intro.mp4",
    location: "Giza Plateau",
    diagram: "Pyramid Overview",
    insight: "Explore the hypothesis that the Great Pyramid was an advanced energy weapon.",
    hypothesis: "Could ancient civilizations have harnessed scalar wave technology?",
  },
  {
    id: "modeling",
    title: "3D Modeling of the Great Pyramid",
    video: "/videos/modeling.mp4",
    location: "Pyramid Base",
    diagram: "Pyramid Dimensions",
    insight: "Accurate modeling reveals the impossibility of construction with Stone Age tools.",
    hypothesis: "What advanced techniques were required for such precision?",
  },
  {
    id: "interior",
    title: "Interior Chambers & Energy Systems",
    video: "/videos/interior.mp4",
    location: "King's Chamber",
    diagram: "Chamber Layout",
    insight: "The internal structure suggests a purpose beyond burial.",
    hypothesis: "Were these chambers designed for energy generation?",
  },
  {
    id: "energy",
    title: "Scalar Wave & Feedback Loops",
    video: "/videos/energy.mp4",
    location: "Resonating Chambers",
    diagram: "Energy Pathways",
    insight: "Feedback loops and scalar wave generators could amplify energy.",
    hypothesis: "How do geometric patterns enhance energy flow?",
  },
  {
    id: "activation",
    title: "Weapon Activation & Simulation",
    video: "/videos/activation.mp4",
    location: "Reactor Core",
    diagram: "Weapon System",
    insight: "Simulations show energy beams targeting celestial bodies.",
    hypothesis: "Could the pyramid have functioned as a directed energy weapon?",
  },
  {
    id: "effects",
    title: "Planetary Effects & Legacy",
    video: "/videos/effects.mp4",
    location: "Solar System",
    diagram: "Energy Trajectory",
    insight: "Energy pulses could have had planetary-scale consequences.",
    hypothesis: "What evidence remains of these ancient technologies?",
  },
  {
    id: "conclusion",
    title: "Conclusion & Future Research",
    video: "/videos/conclusion.mp4",
    location: "Giza Plateau",
    diagram: "Unified Theory",
    insight: "A unified theory of scalar impulse and instantaneous action emerges.",
    hypothesis: "What are the next steps for validating these hypotheses?",
  },
];